// Dữ liệu mẫu quanh Hòa Lạc — chỉ dùng khi CHƯA cấu hình Supabase (.env.local)
export const MOCK_PROPERTIES = [
  {
    id: 'mock-1',
    code: 'HL-001',
    thumbnail: 'https://picsum.photos/seed/hoalac1/640/400',
    title: 'Đất nền 100m2 gần Đại học FPT',
    type: 'Đất nền',
    status: 'available',
    price: 3200000000,
    area: 100,
    frontage: 5,
    road_width: 8,
    direction: 'Đông Nam',
    legal: 'Sổ đỏ',
    address: 'Thạch Hòa, Thạch Thất, Hà Nội',
    lat: 21.0125,
    lng: 105.5254,
    description: 'Lô góc, gần cổng Đại học FPT, đường ô tô tránh nhau.',
  },
  {
    id: 'mock-2',
    code: 'HL-002',
    thumbnail: 'https://picsum.photos/seed/hoalac2/640/400',
    title: 'Đất 120m2 khu CNC Hòa Lạc',
    type: 'Đất nền',
    status: 'deposited',
    price: 4100000000,
    area: 120,
    frontage: 6,
    road_width: 10,
    direction: 'Nam',
    legal: 'Sổ đỏ',
    address: 'Khu CNC Hòa Lạc, Thạch Thất, Hà Nội',
    lat: 21.0043,
    lng: 105.5178,
    description: 'Sát khu công nghệ cao, phù hợp đầu tư dài hạn.',
  },
  {
    id: 'mock-3',
    code: 'HL-003',
    thumbnail: 'https://picsum.photos/seed/hoalac3/640/400',
    title: 'Nhà 3 tầng 80m2 Bình Yên',
    type: 'Nhà ở',
    status: 'available',
    price: 5500000000,
    area: 80,
    frontage: 4.5,
    road_width: 6,
    direction: 'Tây Bắc',
    legal: 'Sổ đỏ',
    address: 'Bình Yên, Thạch Thất, Hà Nội',
    lat: 21.0201,
    lng: 105.5391,
    description: 'Nhà xây mới, full nội thất, gần chợ Bình Yên.',
  },
  {
    id: 'mock-4',
    code: 'HL-004',
    thumbnail: 'https://picsum.photos/seed/hoalac4/640/400',
    title: 'Đất 200m2 mặt đường DH09',
    type: 'Đất nền',
    status: 'sold',
    price: 7800000000,
    area: 200,
    frontage: 8,
    road_width: 12,
    direction: 'Đông',
    legal: 'Sổ đỏ',
    address: 'Tân Xã, Thạch Thất, Hà Nội',
    lat: 21.0158,
    lng: 105.5462,
    description: 'Mặt đường kinh doanh, đã bán tháng 6/2026.',
  },
  {
    id: 'mock-5',
    code: 'HL-005',
    thumbnail: 'https://picsum.photos/seed/hoalac5/640/400',
    title: 'Shophouse 90m2 gần Vin Hòa Lạc',
    type: 'Shophouse',
    status: 'available',
    price: 9200000000,
    area: 90,
    frontage: 6,
    road_width: 15,
    direction: 'Nam',
    legal: 'HĐMB',
    address: 'Đồng Trúc, Thạch Thất, Hà Nội',
    lat: 20.9967,
    lng: 105.5312,
    description: 'Vị trí kinh doanh, dòng tiền cho thuê tốt.',
  },
  {
    id: 'mock-6',
    code: 'HL-006',
    thumbnail: 'https://picsum.photos/seed/hoalac6/640/400',
    title: 'Đất 150m2 Cổ Đông, Sơn Tây',
    type: 'Đất nền',
    status: 'inactive',
    price: 3900000000,
    area: 150,
    frontage: 7,
    road_width: 5,
    direction: 'Bắc',
    legal: 'Sổ đỏ',
    address: 'Cổ Đông, Sơn Tây, Hà Nội',
    lat: 21.0289,
    lng: 105.5127,
    description: 'Chủ tạm ngừng bán, chờ giá.',
  },
];
